#ifndef CONFIG_H
#define CONFIG_H
	//GENERAL
	//SYSTICK
	#define SYSTICK_SIZE 10
	#define SYSTICK_RAZ_INTERVAL 5*60 //RAZ ttes les 5 minutes
	
	#define SYSTICK_TIMER_IT_PRIORITY 1
	
	#define SYSTICK_TIMER TIM1
	#define SYSTICK_TIMER_ARR			1000-1
	#define SYSTICK_TIMER_PSC			36000-1
	
	//ROTATION
	#define ROTATION_DIRECTION_GPIO 			GPIOC
	#define ROTATION_DIRECTION_GPIO_PIN		10

	#define ROTATION_SPEED_GPIO 					GPIOA
	#define ROTATION_SPEED_GPIO_PIN				6

	#define ROTATION_SPEED_TIMER 					TIM3
	#define ROTATION_SPEED_TIMER_CHANNEL	1
	#define ROTATION_SPEED_TIMER_ARR			61-1
	#define ROTATION_SPEED_TIMER_PSC			61-1


	//COMMUNICATION
	#define COMMUNICATION_UART_READ_IT_PRIORITY 0
	
	#define COMMUNICATION_UART USART3
	#define COMMUNICATION_BAUD_RATE 9600
	#define COMMUNICATION_WORD_LENGTH 0
	#define COMMUNICATION_STOP_BITS 1.0
	#define COMMUNICATION_PARITY_CONTROL 0


	#define USART1_GPIO GPIOA
	#define USART1_GPIO_RX_PIN 10
	#define USART1_GPIO_TX_PIN 9

	#define USART2_GPIO GPIOA
	#define USART2_GPIO_RX_PIN 3
	#define USART2_GPIO_TX_PIN 2

	#define USART3_GPIO GPIOB
	#define USART3_GPIO_RX_PIN 11
	#define USART3_GPIO_TX_PIN 10

	#define COMMUNICATION_ALERT_ROULIS "Detection Limite du Roulis"
	#define COMMUNICATION_ALERT_BATTERY "Tension de batterie trop faible"
	
	//BATTERIE
	#define BATTERIE_SYSTIC_PERIOD 3
	#define BATTERIE_LOW_LEVEL	10
	
	#define BATTERIE_ADC_IT_PRIORITY 1
	
	#define BATTERIE_ADC 			ADC1
	#define BATTERIE_ADC_CHANNEL	0
	#define BATTERIE_ADC_SAMPLING	7.5
	#define BATTERIE_ADC_TRIGGER 0x7
	#define BATTERIE_ADC_CC_VALUE 499
	
	#define BATTERIE_GPIO	GPIOA
	#define BATTERIE_GPIO_PIN	0
	
#endif
