#ifndef CONFIG_H
	#define CONFIG_H

	//ROTATION
	#define ROTATION_DIRECTION_GPIO 			GPIOC
	#define ROTATION_DIRECTION_GPIO_PIN		10

	#define ROTATION_SPEED_GPIO 					GPIOA
	#define ROTATION_SPEED_GPIO_PIN				10

	#define ROTATION_SPEED_TIMER 					TIM2
	#define ROTATION_SPEED_TIMER_CHANNEL	2
	#define ROTATION_SPEED_TIMER_ARR			60
	#define ROTATION_SPEED_TIMER_PSC			60


	//COMMUNICATION
	#define COMMUNICATION_UART USART1
	#define COMMUNICATION_BAUD_RATE 9600
	#define COMMUNICATION_WORD_LENGTH 1
	#define COMMUNICATION_STOP_BITS 1.0
	#define COMMUNICATION_PARITY_CONTROL 0


	#define USART1_GPIO GPIOA
	#define USART1_GPIO_RX 10
	#define USART1_GPIO_TX 9

	#define USART2_GPIO GPIOA
	#define USART2_GPIO_RX 3
	#define USART2_GPIO_TX 2

	#define USART3_GPIO GPIOB
	#define USART3_GPIO_RX 11
	#define USART3_GPIO_TX 10

#endif
